### ISSUE TITLE
sintesis 

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/actividad-3-sintesis-Nayee123#2]
[Sintesis_Nayeli Anai Gonzalez Lopez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Nayee123/files/9491134/Sintesis_Nayeli.Anai.Gonzalez.Lopez.pdf)

**Comment by JazminloRI** [comment]
Calificación Final: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
